### PR TITLE
EIN-1 #comment menuda cagada

### PR DESCRIPTION
**Pull request by einarvelez**

### CODE REVIEW

**Comment by einarvelez** [comment]
EIN-1 #in-progress

**Comment by einarvelez** [comment]
EIN-1 #in-progress

**Comment by einarvelez** [comment]
EIN-1 #IN-PROGRESS

**Comment by einarvelez** [comment]
EIN-1 #close

**Comment by einarvelez** [comment]
EIN-1 #en-curso

**Review by einarguisado — APPROVED** [review]

**Pull request merged**
